### ISSUE TITLE
hexo 加载prism出错啦！！！！！

### ISSUE THREAD

**Issue by dark19940411** [ele828/hexo-prism-plugin#20]
我在我的hexo文件夹下安装了prism插件，但是执行hexo clean和hexo g的时候出现了下面的错误log，这是为什么啊？？
`ERROR Plugin load failed: hexo-prism-plugin
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:53:16)
    at /Users/turtle/Desktop/imturtle.cn/node_modules/hexo/lib/hexo/index.js:227:17
    at tryCatcher (/Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at /Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/turtle/Desktop/imturtle.cn/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)`

**Comment by ele828** [comment]
请问node和hexo的版本分别是多少？

**Comment by dark19940411** [comment]
之前版本比较低，现在升到6.10了，但是出现了version mismatch的问题。。。hexo版本信息如下
```
hexo version  

hexo-cli: 1.0.2  
os: Darwin 16.5.0 darwin x64  
http_parser: 2.7.0
node: 6.10.3
v8: 5.1.281.101
uv: 1.9.1
zlib: 1.2.11
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
```

**Comment by dark19940411** [comment]
最低的node和hexo版本要求是多少啊？

**Comment by dark19940411** [comment]
????

**Comment by ele828** [comment]
@dark19940411 不好意思最近比较忙，建议你先把version mismatch的问题解决了。通常来讲，应该是你升级node v6之后没有重新安装node_modules导致的。建议清空node_modules，再重新 npm install 一遍依赖。
