### ISSUE TITLE
Error: template not found: base.html

### ISSUE THREAD

**Issue by changoal** [ele828/hexo-prism-plugin#39]
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  Error: template not found: base.html
    at Object.exports.prettifyError (D:\hexo\node_modules\hexo\node_modules\nunjucks\src\lib.js:34:15)
    at D:\hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:485:31
    at eval (eval at _compile (D:\hexo\node_modules\hexo\node_modules\nunjucks\src\environment.js:564:24), <anonymous>:15:11)

**Comment by ele828** [comment]
Looks like it's not related to hexo-prism-plugin? could you disable it and see if it works?
