### ISSUE TITLE
`prism_plugin` options should be added to _config.yml file

### ISSUE THREAD

**Issue by yanghaoi** [ele828/hexo-prism-plugin#60]
1、I hava a error when I use `hexo clean`:
![image](https://user-images.githubusercontent.com/21354684/89741355-36bc2800-dac3-11ea-8894-e9e5b410e6bb.png)

err: Error: `prism_plugin` options should be added to _config.yml file
      at **\hexo-prism-plugin\src\index.js:70:9
      at **\hexo\lib\hexo\index.js:315:14
      at tryCatcher (**\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (**\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (**\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (**\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (**\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (**\bluebird\js\release\async.js:93:12)
      at _drainQueue (**\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (**\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (**\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
} Plugin load failed: %s hexo-prism-plugin

2、But,`prism_plugin` options is added to _config.yml file    and  my `posts` is worded:
![image](https://user-images.githubusercontent.com/21354684/89741303-a7af1000-dac2-11ea-9625-546869800481.png)

So, this a bug without detriment to work?

**Comment by luwanglin** [comment]
I have the same problem

**Comment by lixinweijy** [comment]
I have the same problem
